databases:
  - name: GalleryApi
    databaseName: postgresql_render_test
    user: admin

services:
  - type: web
    name: GalleryApi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn GalleryApi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql_render_test
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4