# Generated by Django 4.2.7 on 2024-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtApi', '0002_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default=None, upload_to='./public'),
        ),
    ]
