# Generated by Django 4.2.7 on 2024-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtApi', '0004_alter_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default=None, upload_to='ArtApi/static/'),
        ),
    ]
